# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1c48f33a8c557966d7bd8e7c77f9e231"
name = "RTO-Predictor"
application_url = "https://rtify-shopify-application.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true 

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,read_products,read_fulfillments,read_customers,read_shipping,read_assigned_fulfillment_orders,read_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://rtify-shopify-application.onrender.com/auth/callback" ]


